## List vs Array

import to know difference between list and array

What are python lists?
An order sequence of heterogeneous elements

In [3]:
stuff = [1, 'apple', 'foo']
print(stuff[1])

apple


What are python arrays?
An order sequence of homogeneous elements

In [6]:
import array
numbers = array.array('i',[1,2,3,4,5]) #'i' works here because it is a type code, signifies that 'i' only accepts integers
print(numbers)

array('i', [1, 2, 3, 4, 5])


In [4]:
#Iterate over an Array
import array
numbers = array.array('i',[1,2,3,4,5])
for number in numbers:
    print(number)

1
2
3
4
5


## Numpy

Supports N-dimensional Arrays

## 1.Create

In [7]:
!pip install numpy

In [8]:
import numpy as np

In [ ]:
zero_dim = np.arry(23124124)
one_dim = np.array([1,2,3])
two_dim = [[1,2,3,4],[1,2,2,2]] #np.array([1,2,3],[4,5,6])
three_dim = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]]) # number of brackets = number of dimensions
#finds the dim of given array
print(three_dim.ndim) 

In [15]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2,))
full = np.full ((2,2,2,),7)
ones = np.ones((2,2,2))

In [26]:
data
#2 total arrays, 3 arrays, 4 values in each array

array([[[0.44814338, 0.48925635, 0.38330105, 0.90774724],
        [0.50803669, 0.93715877, 0.09790248, 0.20817877],
        [0.38235379, 0.35903626, 0.07946772, 0.05781362]],

       [[0.71834698, 0.71712285, 0.73097744, 0.09250205],
        [0.6985343 , 0.29283683, 0.40373008, 0.72132016],
        [0.00917601, 0.42636467, 0.99878894, 0.57664137]]])

In [27]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [28]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [29]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [18]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 2.Read

In [19]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype

In [20]:
shape

(2, 3, 4)

In [21]:
size

24

In [22]:
types

dtype('float64')

In [23]:
# Slicing
arr = data[0]
slicer = data[0:2]
reverse = data [-1]
singleval = data [0][0][0]

In [24]:
reverse

array([[0.71834698, 0.71712285, 0.73097744, 0.09250205],
       [0.6985343 , 0.29283683, 0.40373008, 0.72132016],
       [0.00917601, 0.42636467, 0.99878894, 0.57664137]])

In [25]:
arr

array([[0.44814338, 0.48925635, 0.38330105, 0.90774724],
       [0.50803669, 0.93715877, 0.09790248, 0.20817877],
       [0.38235379, 0.35903626, 0.07946772, 0.05781362]])

In [30]:
singleval #can be used to specifically point out an item

0.44814338112913943

In [31]:
data

array([[[0.44814338, 0.48925635, 0.38330105, 0.90774724],
        [0.50803669, 0.93715877, 0.09790248, 0.20817877],
        [0.38235379, 0.35903626, 0.07946772, 0.05781362]],

       [[0.71834698, 0.71712285, 0.73097744, 0.09250205],
        [0.6985343 , 0.29283683, 0.40373008, 0.72132016],
        [0.00917601, 0.42636467, 0.99878894, 0.57664137]]])

## 3.Update

In [33]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [39]:
list1

array([0.53930934, 0.73304711, 0.73092226, 0.79185752, 0.03147413,
       0.56306907, 0.45301019, 0.63482234, 0.04588669, 0.23200607])

In [34]:
list2

array([0.67218248, 0.18598312, 0.16927693, 0.05565325, 0.53574521,
       0.59823079, 0.32945977, 0.20494978, 0.00935111, 0.63627134])

In [37]:
# Basic math
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot =np.dot(list1,list2)

In [38]:
add

array([1.21149182, 0.91903024, 0.90019919, 0.84751077, 0.56721934,
       1.16129986, 0.78246996, 0.83977212, 0.0552378 , 0.86827741])

In [48]:
# Stat Functions (SAPLEMM)
sqrt = np.sqrt(25)
ab = np.abs (-2)
power = np.power (2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)